'use client';
import { useEffect, useState } from 'react';
import { Sparkles, TrendingUp, Package, IndianRupee, RefreshCcw, Loader2 } from 'lucide-react';
import { formatINR } from '@/lib/utils';

export default function AnalyticsPage() {
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  const load = async () => {
    setLoading(true);
    const r = await fetch('/api/analytics/insights');
    const d = await r.json();
    setData(d);
    setLoading(false);
  };

  useEffect(() => { load(); }, []);

  return (
    <div className="py-8">
      <div className="flex justify-between items-end mb-6">
        <div>
          <h1 className="text-3xl font-extrabold flex items-center gap-2"><Sparkles className="w-7 h-7 text-primary" /> AI Analytics</h1>
          <p className="text-text2 text-sm mt-1">AI analyzes your data and gives actionable insights.</p>
        </div>
        <button onClick={load} disabled={loading} className="btn btn-ghost text-xs">
          {loading ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <RefreshCcw className="w-3.5 h-3.5" />} Refresh
        </button>
      </div>

      {loading && !data ? (
        <div className="card-base p-10 text-center">
          <Loader2 className="w-10 h-10 mx-auto animate-spin text-primary" />
          <p className="text-text2 text-sm mt-3">AI analyzing your data...</p>
        </div>
      ) : data?.ok ? (
        <>
          {/* Stats */}
          <div className="grid sm:grid-cols-4 gap-4 mb-6">
            <div className="card-base p-5">
              <Package className="w-4 h-4 text-primary mb-2" />
              <div className="text-2xl font-extrabold">{data.stats.orders}</div>
              <div className="text-xs text-text2">Paid orders</div>
            </div>
            <div className="card-base p-5">
              <IndianRupee className="w-4 h-4 text-green-500 mb-2" />
              <div className="text-2xl font-extrabold text-green-500">{formatINR(data.stats.revenue)}</div>
              <div className="text-xs text-text2">Total revenue</div>
            </div>
            <div className="card-base p-5">
              <TrendingUp className="w-4 h-4 text-blue-500 mb-2" />
              <div className="text-2xl font-extrabold text-blue-500">{data.stats.pipelineDeals}</div>
              <div className="text-xs text-text2">CRM deals</div>
            </div>
            <div className="card-base p-5">
              <TrendingUp className="w-4 h-4 text-orange-500 mb-2" />
              <div className="text-2xl font-extrabold text-orange-500">{formatINR(data.stats.pipelineValue)}</div>
              <div className="text-xs text-text2">Pipeline value</div>
            </div>
          </div>

          {/* AI Insights */}
          <div className="card-base p-7 mb-6">
            <h2 className="font-bold flex items-center gap-2 mb-3"><Sparkles className="w-5 h-5 text-primary" /> AI Insights</h2>
            <div className="prose prose-sm dark:prose-invert max-w-none">
              <div className="whitespace-pre-wrap text-sm leading-relaxed text-text">{data.insights}</div>
            </div>
            <div className="mt-4 pt-4 border-t border-tint text-[10px] text-text2">
              Generated by: <span className="font-mono text-primary">{data.provider}</span> · Refresh for new analysis
            </div>
          </div>

          {/* Top Products */}
          {data.stats.topProducts.length > 0 && (
            <div className="card-base p-5">
              <h3 className="font-bold mb-3">Top products</h3>
              <div className="space-y-2">
                {data.stats.topProducts.map((p: any) => (
                  <div key={p.name} className="flex justify-between items-center surface-tint p-3 rounded-lg text-sm">
                    <span className="font-semibold">{p.name}</span>
                    <span className="text-text2">{p.count} orders</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </>
      ) : (
        <div className="card-base p-8 text-center text-red-500">Failed to load insights.</div>
      )}
    </div>
  );
}
